version: '3.5' 

services: 
    front-end: 
      image: front_end
      build: ./frontend/
      ports:
      - 5000:5000
      container_name: front-end

    back-end: 
      image: back_end
      build: ./backend/
      ports:
      - 8000:8000
      command: ./server
      environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=database
      container_name: back-end
      
      
    redis:
      image: redis
      ports:
      - 6379:6379
      container_name: redis

    database:
      image: postgres
      environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      container_name: database
