version: '3.5' 

services: 
    front-end: 
      image: front_end
      build: ./frontend/
      ports:
      - 5000:5000
      container_name: front-end

    back-end: 
      image: back_end
      build: ./backend/
      ports:
      - 8000:8000
      command: ./server
      
      container_name: back-end
